
NUL	= $00	; null value
CR	= $0d	; Carrage return
LF	= $0A	; Line feed

b_WD	= $80	; watchdog bit

ZP_SW1	= $20	; result of switch #1 (call rdSW12)
ZP_SW2	= $21	; result of switch #2 (call rdSW12)
ZP_22	= $22	; rescue 8b (b82HEX))
ZP_LNIB	= $23	; low nibble result of 8b
ZP_HNIB	= $24	; high nibble result of 8b
ZP_25	= $25	; working nibble result
ZP_26	= $26	; last pressed raw key 7279

ZP_29	= $29	; start textbuffer (2 x textlength)



